version: "3.8"
services:
  fauxmail:
    build: .
    container_name: fauxmail
    ports:
      - "8025:8025"   # dashboard
      - "1025:1025"   # smtp
    environment:
      - FAUXMAIL_ADDR=0.0.0.0:8025
      - FAUXMAIL_SMTP_ADDR=0.0.0.0:1025
      - FAUXMAIL_DATABASE=sqlite:///data/fauxmail.db
      # - FAUXMAIL_SMTP_USER=dev
      # - FAUXMAIL_SMTP_PASS=secret
    volumes:
      - ./data:/data
    restart: unless-stopped

  fauxmail_auth:
    build: .
    container_name: fauxmail-auth
    profiles: ["auth"]
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - FAUXMAIL_ADDR=0.0.0.0:8025
      - FAUXMAIL_SMTP_ADDR=0.0.0.0:1025
      - FAUXMAIL_DATABASE=sqlite:///data/fauxmail.db
      - FAUXMAIL_SMTP_USER=dev
      - FAUXMAIL_SMTP_PASS=secret
    volumes:
      - ./data:/data
    restart: unless-stopped
